(()=>{
const q=s=>document.querySelector(s),qa=s=>[...document.querySelectorAll(s)];
const A={L:192/361,M:117/361,S:52/361};
function counts(){const m=q('input[name="mode"]:checked')?.value;if(m==='full'){const n=Math.max(1,parseInt(q('#fullCount')?.value)||1);return{L:n,M:n,S:n}}return{L:Math.max(0,parseInt(q('#largeCount')?.value)||0),M:Math.max(0,parseInt(q('#mediumCount')?.value)||0),S:Math.max(0,parseInt(q('#smallCount')?.value)||0)}}
function values(){const c=counts(),af=A.L*c.L+A.M*c.M+A.S*c.S;return{nutella:200*c.L,kinder:112.5*c.M,bueno:2*c.M,blanco:45*c.S,mascarpone:250*c.L+140*c.M+62.5*c.S+250*af,nata:120*c.L+67.5*c.M+30*c.S+750*af,glas:110*af}}
function fmt(v,u){if(u==='g'&&v>=1000)return(v/1000).toFixed(2).replace(/0+$/,'').replace(/\.$/,'')+' kg';if(u==='ml'&&v>=1000)return(v/1000).toFixed(2).replace(/0+$/,'').replace(/\.$/,'')+' l';return Number(v.toFixed(u==='barritas'?0:1))+' '+u}
const map={'Nutella':['nutella','g'],'Crema Kinder':['kinder','g'],'Kinder Bueno':['bueno','barritas'],'Chocolate blanco':['blanco','g'],'Mascarpone total':['mascarpone','g'],'Nata 35 % total':['nata','ml']};
const packs={'Nutella':['g',350],'Crema Kinder':['g',200],'Kinder Bueno':['barritas',6],'Chocolate blanco':['g',200],'Mascarpone total':['g',250],'Nata 35 % total':['ml',500]};
function patch(){const v=values();qa('#recipeDynamic .dyn,#shoppingList .shop').forEach(el=>{const name=el.querySelector('strong')?.textContent?.trim(),spec=map[name];if(!spec)return;const amount=el.querySelector('.amount');if(amount)amount.textContent=fmt(v[spec[0]],spec[1])});qa('#mercadonaList .merc').forEach(el=>{const name=el.querySelector('h3')?.textContent?.trim(),spec=map[name];if(!spec)return;const a=v[spec[0]],u=spec[1],p=packs[name],num=Math.ceil(a/p[1]),bought=num*p[1],metrics=el.querySelectorAll('.metric strong');if(metrics[0])metrics[0].textContent=fmt(a,u);if(metrics[1])metrics[1].textContent=num+' '+(num===1?'envase':'envases')+' × '+p[1]+' '+p[0];if(metrics[2])metrics[2].textContent=fmt(bought-a,u)});const total=q('#usefulTotals');if(total){const old=total.innerHTML;total.innerHTML=old.replace(/mascarpone\s+[^·]+/i,'mascarpone '+fmt(v.mascarpone,'g')+' ').replace(/nata\s+[^·]+/i,'nata '+fmt(v.nata,'ml')+' ')}}
function schedule(){setTimeout(patch,20);setTimeout(patch,120)}
document.addEventListener('DOMContentLoaded',()=>{schedule();['fullCount','largeCount','mediumCount','smallCount'].forEach(id=>q('#'+id)?.addEventListener('input',schedule));qa('input[name="mode"]').forEach(x=>x.addEventListener('change',schedule));document.addEventListener('click',e=>{if(e.target?.classList?.contains('tab-btn'))schedule()})});
})();