(()=>{
  const steps=document.getElementById('steps');
  if(!steps) return;
  steps.innerHTML=`
  <label class="step"><input type="checkbox"><div><strong>1 · Prepara los moldes</strong><p>Forra las bases y laterales de los moldes seleccionados. Precalienta a 165–170 °C, calor arriba y abajo, rejilla medio-baja.</p></div></label>
  <label class="step"><input type="checkbox"><div><strong>2 · Bate huevos y azúcar</strong><p>Con las varillas eléctricas dobles, bate 4–5 minutos a velocidad media-alta hasta que la mezcla esté clara, espumosa y con bastante volumen.</p></div></label>
  <label class="step"><input type="checkbox"><div><strong>3 · Añade yogur, vainilla y aceite</strong><p>Baja la velocidad. Incorpora el yogur griego y la vainilla. Añade el aceite en hilo fino y mezcla sólo hasta integrar.</p></div></label>
  <label class="step"><input type="checkbox"><div><strong>4 · Incorpora la harina</strong><p>Tamiza la harina. Si utilizas harina de repostería con impulsor incorporado, no añadas impulsor adicional. Mezcla a mano con varilla o espátula, en 2–3 tandas y sin sobrebatir.</p></div></label>
  <label class="step"><input type="checkbox"><div><strong>5 · Reparte y hornea</strong><p>Distribuye la masa según los tamaños seleccionados y usa la pestaña Horneado para sincronizar los moldes. Retira cada uno cuando la brocheta salga limpia o con pocas migas húmedas.</p></div></label>
  <label class="step"><input type="checkbox"><div><strong>6 · Enfría completamente</strong><p>Deja 10–15 minutos en el molde, desmolda y pasa a una rejilla. No rellenes mientras el bizcocho conserve calor.</p></div></label>
  <label class="step"><input type="checkbox"><div><strong>7 · Relleno de Nutella · piso grande</strong><p>Mascarpone y Nutella deben estar fríos. Bate primero mascarpone + Nutella a velocidad baja-media sólo hasta homogeneizar. Añade la nata muy fría y sube a velocidad media. Para en cuanto forme picos firmes. No sigas batiendo o puede cortarse.</p></div></label>
  <label class="step"><input type="checkbox"><div><strong>8 · Relleno Kinder Bueno · piso mediano</strong><p>Mezcla mascarpone + crema Kinder hasta homogeneizar. Incorpora la nata muy fría y monta a velocidad media hasta obtener una crema firme. Añade al final el Kinder Bueno troceado o triturado con espátula, sin volver a batir fuerte.</p></div></label>
  <label class="step"><input type="checkbox"><div><strong>9 · Relleno de chocolate blanco · piso pequeño</strong><p>Derrite el chocolate blanco suavemente y deja que baje aproximadamente a 28–30 °C: debe estar fluido pero no caliente. Mezcla con el mascarpone. Incorpora la nata fría y bate a velocidad media hasta que la crema quede firme. Si el chocolate está caliente, ablandará la crema.</p></div></label>
  <label class="step"><input type="checkbox"><div><strong>10 · Monta y rellena cada piso</strong><p>Nivela los bizcochos si es necesario. Puedes humedecerlos ligeramente con almíbar. Rellena cada piso con su crema correspondiente sin llegar completamente al borde. Refrigera cada piso 20–30 minutos antes de cubrirlo.</p></div></label>
  <label class="step"><input type="checkbox"><div><strong>11 · Prepara la cobertura de nata y mascarpone</strong><p>Enfría bol, nata y mascarpone. Pon mascarpone y azúcar glas en el bol y mezcla brevemente a velocidad baja. Añade la nata muy fría y monta a velocidad media, vigilando continuamente. Detente cuando forme picos firmes y conserve una textura lisa. No busques una textura granulada: sería señal de exceso de batido.</p></div></label>
  <label class="step"><input type="checkbox"><div><strong>12 · Capa recogemigas</strong><p>Antes de colorear, usa una pequeña parte de cobertura blanca para aplicar una capa muy fina a cada piso. Refrigera 20–30 minutos hasta que quede firme.</p></div></label>
  <label class="step"><input type="checkbox"><div><strong>13 · Divide y colorea la cobertura</strong><p>Divide la cobertura restante según la cantidad necesaria para cada piso. <strong>Morado:</strong> mezcla azul + una cantidad menor de rojo; empieza aproximadamente con 2 partes de azul por 1 de rojo y corrige gota a gota. <strong>Rosa:</strong> usa una cantidad mínima de rojo sobre crema blanca. <strong>Azul:</strong> añade azul progresivamente. Mezcla cada color suavemente con espátula, no con batidora. Los geles intensifican el tono tras unos minutos: espera antes de añadir más.</p></div></label>
  <label class="step"><input type="checkbox"><div><strong>14 · Cubre cada piso</strong><p>Grande → morado. Mediano → rosa. Pequeño → azul. Aplica primero una capa generosa, alisa laterales y parte superior con espátula o rasqueta y refrigera antes del montaje definitivo.</p></div></label>
  <label class="step"><input type="checkbox"><div><strong>15 · Soportes y montaje</strong><p>Coloca base fina bajo los pisos medio y pequeño. Introduce dowels o soportes en los pisos inferiores, córtalos exactamente a nivel y apila los pisos centrados.</p></div></label>
  <label class="step"><input type="checkbox"><div><strong>16 · Acabado y frío final</strong><p>Corrige juntas y pequeños huecos con la cobertura del color correspondiente. Refrigera la tarta terminada al menos 4–6 horas; idealmente toda la noche. Sácala unos 15–20 minutos antes de servir.</p></div></label>
  <div class="note warn" style="grid-column:1/-1"><strong>Colorantes en gel Dr. Oetker:</strong> son adecuados para la cobertura. Añade cantidades muy pequeñas con un palillo o una gota cada vez. Para el morado, no mezcles grandes cantidades de rojo y azul de golpe: es fácil obtener un tono demasiado oscuro.</div>`;
})();
